include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Tesla 3-6-9 Coding Standards
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false  # Allow print for consciousness logging
    use_key_in_widget_constructors: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore
